### ISSUE TITLE
Bug - Resetting Server

### ISSUE THREAD

**Issue by binxce** [mbax/Portals#2]
Everytime I reset my server the plugin shows a bunch of console errors, so then i have to delete all the warps / portals i have made and create them again, this process is getting very annoying...

Listener.java:517)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 24 more
20:56:42 [SEVERE] Could not pass event PlayerMoveEvent to Portals v1.2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:
219)
        at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)

```
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:
```

112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30
)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:59
8)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:22
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:49
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:
427)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:84
9)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftPlayer.teleport(CraftPlayer
.java:382)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftEntity.teleport(CraftEntity
.java:189)
        at meeees.plugins.Portals.DetectOn.playerMoved(DetectOn.java:67)
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 14 more
20:56:42 [SEVERE] Could not pass event PlayerTeleportEvent to Random Spawn v2.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftPlayer.teleport(CraftPlayer
.java:369)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftEntity.teleport(CraftEntity
.java:189)
        at meeees.plugins.Portals.DetectOn.playerMoved(DetectOn.java:67)
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:
219)
        at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)

```
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:
```

112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30
)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:59
8)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:22
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:49
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:
427)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:84
9)
Caused by: java.lang.NullPointerException
        at org.bukkit.Location.getChunk(Location.java:73)
        at me.Josvth.RandomSpawn.RandomSpawn.sendGround(RandomSpawn.java:204)
        at me.Josvth.RandomSpawn.Listeners.JoinListener.onPlayerTeleport(JoinLis
tener.java:30)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 24 more
20:56:42 [SEVERE] Could not pass event PlayerTeleportEvent to Multiverse-Core v2
.4-b527
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftPlayer.teleport(CraftPlayer
.java:369)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftEntity.teleport(CraftEntity
.java:189)
        at meeees.plugins.Portals.DetectOn.playerMoved(DetectOn.java:67)
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:
219)
        at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)

```
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:
```

112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30
)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:59
8)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:22
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:49
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:
427)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:84
9)
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTele
port(MVPlayerListener.java:193)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 24 more
20:56:42 [SEVERE] Could not pass event PlayerTeleportEvent to pvparena v0.10.2.3
4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftPlayer.teleport(CraftPlayer
.java:369)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftEntity.teleport(CraftEntity
.java:189)
        at meeees.plugins.Portals.DetectOn.playerMoved(DetectOn.java:67)
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:
219)
        at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)

```
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:
```

112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30
)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:59
8)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:22
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:49
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:
427)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:84
9)
Caused by: java.lang.NullPointerException
        at net.slipcor.pvparena.classes.PABlockLocation.<init>(PABlockLocation.j
ava:31)
        at net.slipcor.pvparena.listeners.PlayerListener.onPlayerTeleport(Player
Listener.java:517)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 24 more
20:56:42 [SEVERE] Could not pass event PlayerMoveEvent to Portals v1.2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:
219)
        at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)

```
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:
```

112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30
)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:59
8)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:22
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:49
4)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:
427)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:84
9)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftPlayer.teleport(CraftPlayer
.java:382)
        at org.bukkit.craftbukkit.v1_4_6.entity.CraftEntity.teleport(CraftEntity
.java:189)
        at meeees.plugins.Portals.DetectOn.playerMoved(DetectOn.java:67)
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 14 more
20:56:50 [INFO] binxce issued server command: /warp main
20:56:52 [INFO] binxce issued server command: /gm 1
20:57:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:57:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:57:36 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:57:36 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:58:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:58:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:58:35 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:58:35 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:59:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:59:05 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:59:18 [WARNING] Can't keep up! Did the system time change, or is the server o
verloaded?
20:59:36 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:59:36 [INFO] SG - STOPPED LOBBY CHUNK FROM UNLOADING!
20:59:47 [WARNING] Can't keep up! Did the system time change, or is the server o
verloaded?
21:00:03 [WARNING] Can't keep up! Did the system time change, or is the server o
verloaded?

By the looks of it it [MAY] be interfering with another plugin i have called PVP Arena

**Comment by mbax** [comment]
"meeees.plugins.Portals.DetectOn.playerMoved"

Yeah, this isn't this plugin
